version: '3.5'

services:
  neo4j:
    image: neo4j:3.5
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "neo4j/cassandra"
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_dbms_security_procedures_unrestricted : 'apoc.*'
    volumes:
      - ./neo4j/plugins:/plugins
    networks:
      app_net:
        ipv4_address: 172.18.1.3

  blog-cassandra:
    image: "cassandra:3.11.9"
    container_name: "blog-cassandra"
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    networks:
      app_net:
        ipv4_address: 172.18.1.2

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"

