version: '3.5'

services:
  neo4j:
    image: neo4j:3.5
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "neo4j/mongo"
      NEO4J_apoc_export_file_enabled: 'true'
    volumes:
      - ./neo4j/plugins:/plugins
    networks:
      app_net:
        ipv4_address: 172.18.1.2


  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: neo4j
    ports:
      - 27017:27017
    volumes:
      - ./mongo/dump:/dump
    networks:
      app_net:
        ipv4_address: 172.18.1.3


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: neo4j
    networks:
      app_net:
        ipv4_address: 172.18.1.4

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"

